language: r
cache: packages
r: release

env:
    - BIODB_USERAGENT="biodbUniprot.test ; pierrick.roger@cea.fr"

notifications:
    email:
        recipients:
            - pierrick.roger@cea.fr

before_install:
    - R -e 'install.packages("BiocManager");BiocManager::install("BiocCheck")'
    - PATH="$PATH:$HOME/R/Library/BiocCheck/script" # Add BiocCheck script dir to PATH because of failure while installing scripts to /opt/R/4.0.2/lib/R/bin (owned by root) as travis user.
    - R -e 'install.packages("devtools", dependencies=TRUE)'
    - R -e 'devtools::install_github("pkrog/biodb", ref="master", dependencies=TRUE, build_vignettes=FALSE)'

script:
    - make test
    - make build
    - make full.check || (cat /home/travis/build/pkrog/biodbUniprot/biodbUniprot.Rcheck/tests/testthat.Rout.fail && false)
    - make bioc.check
